### ISSUE TITLE
Support bold math commands \bm and \symbf

### ISSUE THREAD

**Issue by mb21** [jgm/texmath#101]
There are a variety of ways to typeset bold math in LaTeX, but the [most used ones seem to be](https://tex.stackexchange.com/questions/595/how-can-i-get-bold-math-symbols):

- `\mathbf` (already supported by texmath)
- `\boldsymbol` (supported since https://github.com/jgm/texmath/issues/67) and `\pmb` (faked bold), both from the `amsbsy` package
- `\bm` from the [bm package](http://www.ctan.org/pkg/bm), see https://github.com/jgm/texmath/pull/26, not to be confused with `\bf` (recommended by some as the best option for LaTeX, but not supported by MathJax)
- `\symbf` from the [unicode-math](https://ctan.org/pkg/unicode-math) package
- `\boldmath` (not supported by MathJax and deemed out-of-scope for texmath in https://github.com/jgm/texmath/issues/93)

Since `\pmb` is only faked bold this shouldn't be in wide use, only`\bm` and `\symbf` remain to be supported by texmath.

AFAIK both of these should be only used in the math environment (e.g. `\bm` gives a "missing dollar inserted" warning otherwise).

**Comment by jgm** [comment]
`\bm` is already supported in texmath.

Should `\symbf` produce the same kind of result as `\bm`?

**Comment by mb21** [comment]
> `\bm` is already supported in texmath.

ah, so pull #26 can be closed then..?

> Should `\symbf` produce the same kind of result as `\bm`?

Yes, AFAIK it basically does for Lua- and XeLaTeX what `\bm` does for pdfLaTeX.
