### ISSUE TITLE
Special characters not supported at 2.0.1.1 version

### ISSUE THREAD

**Issue by erimpapova** [jgm/texmath#106]
While working properly on version 1.19.2.1, in the current 2.0.1.1 version the special characters (# $ % & ~ _ ^ \ { }) are not supported (not parsed).

**Comment by jgm** [comment]
I'm not sure what you mean.  Can you give some examples of
things that you think should work, including the output you
get?  (You can use the texmath executable to test.)

+++ erimpapova [Nov 16 17 08:41 ]:
>   While working properly on version 1.19.2.1, in the current 2.0.1.1
>   version the special characters (# $ % & ~ _ ^ \ { }) are not supported
>   (not parsed).
>

**Comment by erimpapova** [comment]
For example, if we pasted Latex format like 'Peter & Farindon' in version
1.19.2.1 earlier then we got 'Peter & Farindon' after parsing/convertion.
Currently, in version 2.0.1.1 we need to paste 'Peter \& Farindon' to get a
desired 'Peter & Farindon' text. Is this a normal behaviour or it's a bug?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jgm** [comment]
Give me the entire math snippet you're using.
"Peter & Farindon" doesn't sound like math, and anyway
'&' is a special character in LaTeX...

+++ erimpapova [Nov 21 17 08:22 ]:

**Comment by erimpapova** [comment]
I'm sorry, it looks like my question is not related to texmath. Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
