### ISSUE TITLE
Unicode → TeX functionality not usable

### ISSUE THREAD

**Issue by slakkenhuis** [jgm/texmath#108]
`Text.TeXMath.Unicode.ToTeX` exposes the `getTeXMath` function, but this function returns a `TeX` type which does not seem to be in any way usable externally (since both the `TeX` datatype and `renderTeX` are defined in the hidden module `Text.TeXMath.TeX`).

Can Text.TeXMath.TeX be exposed? (If not, I'd be happy to write an additional `getTeXMathString` function.)

My use case is that I would like to use texmath as a library to translate strings like `φ ∧ ψ` to `\phi \land \psi`.

**Comment by jgm** [comment]
Sure, I can do that.

+++ slakkenhuis [Dec 22 17 06:21 ]:
