### ISSUE TITLE
\uppi, \mathrel display wrongly

### ISSUE THREAD

**Issue by TitanSnow** [jgm/texmath#109]
`\uppi`, `\upphi`, etc is still italic.

There's no space around `\mathrel`, `\mathbin`, etc.

Example:
```latex
$$
S = \uppi r^2
$$

$$
S = \mathrm{\pi} r^2
$$

$$
a > b \mathrel{\text{or}} a > c
$$
```

Output of `pdflatex`:
![default](https://user-images.githubusercontent.com/19969470/34413280-4b83c6a4-ec1d-11e7-9aba-abb6e2406a0c.png)

Output of `pandoc -t docx` (with `texmath 0.10`)
![2](https://user-images.githubusercontent.com/19969470/34413310-88687bd2-ec1d-11e7-9f8d-3466d64c268a.png)

**Comment by TitanSnow** [comment]
It's still wrong — the text operator is now italic:
![default](https://user-images.githubusercontent.com/19969470/35390318-df5a53b4-01d2-11e8-9b5d-fa8ef57af0b0.png)

**Comment by jgm** [comment]
We're not explicitly telling it to use italics, so I suppose this is some kind of default.
