### ISSUE TITLE
Microsoft Word to Mediawiki markup problem with equation to <math> markup when Greek letters present

### ISSUE THREAD

**Issue by markdhenning** [jgm/texmath#114]
John MacFarlane asked that I submit this report  @jgm 

We are using Pandoc to transform a lot of scientific papers from MS word to a mediawiki system.  We have come across a significant problem: 

Equation translation is nearly perfect, but if there are terms that include Greek symbols (see embedded equation above)  the clause TrVC is being set as a single \text{TrVC}.  Latex considers this a parse error.  Changing it by hand to \text{T}\rho\text{VC} fixes the parse error.  
![equationexample](https://user-images.githubusercontent.com/35781681/35356061-36bd6038-0147-11e8-8602-721ed1cde357.png)

Thank you for your support!

**Comment by jgm** [comment]
You refer to "embedded equation above" but there is nothing above?

**Comment by jgm** [comment]
You never clarified what the embedded equation is. But I suspect the changes in 0.11 will fix this issue.
