### ISSUE TITLE
Inconsistent textrm and blank characters between docx and pdf

### ISSUE THREAD

**Issue by ColinKinloch** [jgm/texmath#117]
Example of a few cases of inconsistent rendering.

- [ ] Docx "+" operator requires operands e.g. {} or "" for blank characters
- [ ] \textrm renders text as italic. Adding nitalic before a string is a work around.
- [ ] \textrm allows the keyword nitalic into the final document (helpful for workarounds)

For the docx notation nitalic is applied until the end of a word or to a complete string inside quotation marks.

```
$nitalic$ $\textrm{nitalic}$

docx
----

$2 \textrm{nitalic NO}^{-}_{3} + 10 e^{-} + 12 \textrm{nitalic H}^{+\textrm{""}} \to \textrm{nitalic N}_{2} + 6 \textrm{nitalic H}_{2} \textrm{nitalic O}$

$n^{0} + \textrm{""}_{3}^{6}\textrm{nitalic Li} \to \textrm{""}^{3}_{1}\textrm{nitalic T} + \textrm{""}_{2}^{4}\textrm{nitalic He} + 4.784 \textrm{nitalic MeV}$

$\textrm{nitalic Hello World}$ $\textrm{nitalic "Hello World"}$ $\textrm{nitalic {Hello World}}$

pdf
---

$2 \textrm{NO}^{-}_{3} + 10 e^{-} + 12 \textrm{H}^{+} \to \textrm{N}_{2} + 6 \textrm{H}_{2} \textrm{O}$

$n^{0} + {}_{3}^{6}\textrm{Li} \to {}^{3}_{1}\textrm{T} + {}_{2}^{4}\textrm{He} + 4.784 \textrm{MeV}$

$\textrm{Hello World}$
```

<img width="1141" alt="repandoc" src="https://user-images.githubusercontent.com/334272/39473055-e0531d10-4d44-11e8-8dfd-7f35416e3f4e.png">

[repandox.docx](https://github.com/jgm/texmath/files/1963773/repandox.docx)
[repandox.pdf](https://github.com/jgm/texmath/files/1963774/repandox.pdf)

**Comment by jgm** [comment]
What version of texmath (and pandoc) are you using?

**Comment by ColinKinloch** [comment]
pandoc 2.2, texmath 0.10.1.2

installed using brew
```
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.1
Default user data directory: /Users/ckinloch/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by ColinKinloch** [comment]
[repandox.docx](https://github.com/jgm/texmath/files/1960390/repandox.docx)
[repandox.pdf](https://github.com/jgm/texmath/files/1960391/repandox.pdf)

**Comment by jgm** [comment]
Sorry, I don't really understand this issue report.
I opened your repandox.docx in Word, and what I saw is not what you present in the image:

<img width="396" alt="screen shot 2018-05-10 at 8 56 26 pm" src="https://user-images.githubusercontent.com/3044/39905895-a685c87e-5494-11e8-9fa5-fda0769b8b83.png">

Here the textrm bits show up without italics, for example.
'nitalic' just renders as a word.
What version of Word are you using?  (Or is it Word?)

**Comment by ColinKinloch** [comment]
You're right, I'm using LibreOffice.
I'll report the issue to them.

Is there a way to get rid of the gaps when super and subscript characters are attached to a blank space?

This test exhibits some issues when converting to odt but I'll open another issue for that for clarity.

**Comment by jgm** [comment]
Colin Kinloch <notifications@github.com> writes:

> Is there a way to get rid of the gaps when super and subscript characters are attached to a blank space?

I'd like to figure out how to do that, if possible.
Open a separate issue?

One thing that seems to work okay is inserting a zero-width
space in the m:e element (instead of leaving empty).
