### ISSUE TITLE
to omm add empty m:t in front of sub

### ISSUE THREAD

**Issue by yuanxu** [jgm/texmath#118]
version: 0.10.1.2

LateX:  _{62}^{144}{Sm}

`
<m:oMathPara>
  <m:oMathParaPr>
    <m:jc m:val="center" />
  </m:oMathParaPr>
  <m:oMath>
    <m:sSubSup>
      <m:e>
        <m:r>
          <m:t></m:t>
        </m:r>
      </m:e>
      <m:sub>
        <m:r>
          <m:t>62</m:t>
        </m:r>
      </m:sub>
      <m:sup>
        <m:r>
          <m:t>144</m:t>
        </m:r>
      </m:sup>
    </m:sSubSup>
    <m:r>
      <m:t>S</m:t>
    </m:r>
    <m:r>
      <m:t>m</m:t>
    </m:r>
  </m:oMath>
</m:oMathPara>
`

**Comment by jgm** [comment]
Why is this needed?  Can you explain?

**Comment by jgm** [comment]
Does adding the empty m:t make the dotted box go away?
I thought I had tried that, to no effect.

**Comment by jgm** [comment]
Removing the `<m:r><m:t></m:t></m:r>` doesn't make the dotted box go away.

**Comment by jgm** [comment]
@yuanxu I found a way:  I insert zero-width spaces.
The new release 0.11.0.1 has this fix, and no dotted boxes.
