### ISSUE TITLE
Latex-equations to word 2016 creates wrong output

### ISSUE THREAD

**Issue by TherMaTh** [jgm/texmath#119]
When I convert $P V = \dot{m} R T$ from latex/org/markdown to a Word-file the dot above the m will be placed in the wrong position. The dot is placed a little bit to the left compared to if I write the equation directly in Word. Is there a simple fix for this? I use Pandoc version 2.2.3.2

I use pandoc file_with_latex_equation.org -f org -t docx -s -o output.docx 

![equation](https://user-images.githubusercontent.com/28752968/45267397-ddc55e80-b46b-11e8-9377-dc68d4ae17f5.png)

**Comment by jgm** [comment]
Looks like word uses `m:acc` instead of `m:groupChr`.  Another potential difference is the italics property.


``` xml
          <m:acc>
            <m:accPr>
              <m:chr m:val="&#204;&#8225;" />
              <m:ctrlPr>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:i />
                </w:rPr>
              </m:ctrlPr>
            </m:accPr>
            <m:e>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                </w:rPr>
                <m:t>m</m:t>
              </m:r>
            </m:e>
          </m:acc>
```
