### ISSUE TITLE
Math bold italic converted as bold content in docx conversion

### ISSUE THREAD

**Issue by sounder27** [jgm/texmath#123]
Bold italic in math content is converted as only bold content at word conversion from xhtml. 
Kindly provide solution to solve it.

<m:math><m:mrow><m:mi mathvariant="bold-italic">w</m:mi></m:mrow><m:mo>=</m:mo><m:mi>m</m:mi><m:mrow><m:mi mathvariant="bold-italic">g</m:mi></m:mrow></m:math>

**Comment by jgm** [comment]
I see now that this isn't a texmath issue.
Closing in favor of jgm/pandoc#4971.
