### ISSUE TITLE
Add support to siunitx

### ISSUE THREAD

**Issue by cristobaltapia** [jgm/texmath#132]
Hi,

I think it would be a good idea to implement support for the `siunitx` commands (e.g. `\SI{...}{...}`, `\si{...}`), as done in pandoc. Currently, the commands used inside a math environment don't get parsed as they do outside of it, which is a bit inconsistent. I don't know how texmath (or pandoc) is implemented, but I suppose that there is a lot of code that can be taken from pandoc's implementation of this feature?

**Comment by jgm** [comment]
Closed by d34664eb6d3bb378bfc0bc60c8243c729a0c6f6e
