### ISSUE TITLE
pandoc cannot recognize limit operators(math) in docx

### ISSUE THREAD

**Issue by redstoneleo** [jgm/texmath#133]
I have tried `pandoc-2.6-windows-i386` to convert `a.docx` containing limit formula to Markdown by the command 
`E:\pandoc-2.6-windows-i386\pandoc.exe -s a.docx  -t markdown-smart --wrap=none -o example35.md`

While it seems pandoc cannot recognize limit operators, one could test the problem with 
[a.docx](https://github.com/jgm/pandoc/files/2921954/a.docx)

**Comment by redstoneleo** [comment]
Thanks very much !
I need to use the fixed pandoc to do the conversion as soon as possible, and I also found the [compiling process](https://github.com/jgm/pandoc/blob/master/INSTALL.md#compiling-from-source) a bit complicated, could you release a new version of pandoc ?

**Comment by jgm** [comment]
I will be releasing a new pandoc shortly.
