### ISSUE TITLE
commitBuffer: invalid argument (invalid character) at version 0.11.2.2

### ISSUE THREAD

**Issue by views63** [jgm/texmath#137]
Example:
In test.tex:
`\iiint_{0}^{1}f\left( x \right)\mathbb{d}x`

use `texmath test.tex` output:

> <math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
>   <mrow>
>     <msubsup>
>       <mo>texmath: <stdout>: commitBuffer: invalid argument (invalid character)
![图片](https://user-images.githubusercontent.com/175116/54922318-d6b2f900-4f42-11e9-9f69-6d8e568eaf55.png)

**Comment by jgm** [comment]
This is a Windows console issue, not a texmath issue. Texmath is producing UTF-8 output, and my guess is that you don't have your Windows console set up right to accept that.

**Comment by thrasher824** [comment]
console use "chcp 65001"
