### ISSUE TITLE
MathML output for inline LaTeX $\underline{Z}$ has a wrong attribute

### ISSUE THREAD

**Issue by kellnerd** [jgm/texmath#142]
I often use inline LaTeX formulas in pandoc's markdown to convert my documents to HTML with MathML formulas. When I use `$\underline{Z}` for complex notation, the line in the output is lower than it should be, meaning there is too much distance between the line and the letter Z.

### Command line & Input

This is a minimal example that was tested with pandoc version 2.7.3

```bash
$ pandoc --mathml -o test.html
$\underline{Z}$
````

### Expected output

```html
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><munder><mi>Z</mi><mo accent="true">̲</mo></munder><annotation encoding="application/x-tex">\underline{Z}</annotation></semantics></math></p>
```

### Actual output

```html
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><munder><mi>Z</mi><mo accent="false">̲</mo></munder><annotation encoding="application/x-tex">\underline{Z}</annotation></semantics></math></p>
```

The wrong display is caused by the attribute `accent="false"` in the [`<mo>`-tag](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo) that should be `accent="true"` in the case of a line that _accentuates_ the letter Z.

**Comment by jgm** [comment]
I'm not sure what principle should be applied here. After all, `\underline{}` can go around anything and in general it's not an "accent."

**Comment by kellnerd** [comment]
If you have a look at the documentation of the surrounding element [`<munder>`](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munder), you can see that it has a similar attribute `accentunder` that differentiates between limits and accentuation:

> If `true`, the element is an _accent_, which is drawn closer to the base expression.
> If `false `(default value), the element is a _limit_ under the base expression.

In my opinion `\underline{}` is an accentuation/emphasis/highlighting in every case and not a limit like in `\sum_k`. If you disagree, can you please provide me an example where this is not correct?

An example where pandoc uses `<mo accent="true">` (as it should be) is `$\underbrace{\sin(\omega t)}$`:

```html
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><munder><mrow><mo>sin</mo><mo stretchy="false" form="prefix">(</mo><mi>ω</mi><mi>t</mi><mo stretchy="false" form="postfix">)</mo></mrow><mo accent="true">⏟</mo></munder><annotation encoding="application/x-tex">\underbrace{\sin(\omega t)}</annotation></semantics></math></p>
```

**Comment by jgm** [comment]
`\underline{Z}` gets parsed as
```
EUnder False (EIdentifier "Z") (ESymbol TUnder "\818")
```
In rendering `ESymbol` to MathML, texmath calls `getMathMLOperator` to determine whether `accent` should be set to true. This function is based on a lookup table that is generated from data  `unicode.xml` -- see texmath/lib/mmldict.  It seems that the accent attribute is set to true when you have
```
<operator-dictionary ... accent="true"/>
```
and that isn't the case for `0332` (hex 818).

The solution may simply be to use a different character when parsing `\underline`.  It seems that regular `_` has the right attributes, actually, though this may cause problems with other output formats.
