### ISSUE TITLE
Pandoc fails when found subscript in "\operatorname" in LaTeX document

### ISSUE THREAD

**Issue by Zmuogs** [jgm/texmath#147]
I can't convert LaTeX document where "**\operatorname**" contains a subscript. _pdflatex_ and online editors have no complains and produces correct output.
 There is [formules.tex.zip](https://github.com/jgm/texmath/files/3906327/formules.tex.zip) file content:
```
\documentclass{article}
\begin{document}
    \( h_{T} \)
    \begin{dmath}
        \operatorname{a}{\left (t \right )}
    \end{dmath}
    \begin{dmath}
        \operatorname{x_{1}}{\left (t \right )} = \operatorname{l_{1}}{\left (t \right )} \sin{\left (\theta_{1}{\left (t \right )} \right )} + \operatorname{x_{T}}{\left (t \right )}
    \end{dmath}
    \begin{dmath}
        \operatorname{b_{T}}{\left (t \right )}
    \end{dmath}
\end{document}
```

 Command I using:
```
pandoc -f latex -t odt -o output.odt formules.tex
```
produces this output:
```
[WARNING] Could not convert TeX math '\operatorname{x_{1}}{\left (t \right )} = \operatorname{l_{1}}{\left (t \right )} \sin{\left (\theta_{1}{\left (t \right )} \right )} + \operatorname{x_{T}}{\left (t \right )}', rendering as TeX:
  operatorname{x_{1}}{\left (t \right )} =
                     ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
[WARNING] Could not convert TeX math '\operatorname{b_{T}}{\left (t \right )}', rendering as TeX:
  operatorname{b_{T}}{\left (t \right )}
                     ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```
 I using Linux (Kubuntu 19.10) and "Pandoc -v":
```
pandoc 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
```

**Comment by jgm** [comment]
Unfortunately this isn't easy to fix at the moment, since our type for OperatorName just takes a textual value as argument.

**Comment by Zmuogs** [comment]
I found another (maybe related) problem:  when converting [a.tex.zip](https://github.com/jgm/texmath/files/3907103/a.tex.zip) (using same command as in first post) I getting additional complain about **\textup** which resides in subscript:
``` 
[WARNING] Could not convert TeX math 'b_{\textup{T}}{\left (t \right )}', rendering as TeX:
  b_{\textup{T}}{\left (t \right )}
            ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```
_pdflatex_ has no complains and produces correct output:
![Screenshot_20191130_141417](https://user-images.githubusercontent.com/20404470/69900517-11481d80-137d-11ea-96df-0e735a57cdcd.png)

**Comment by jgm** [comment]
I think the problem there is that texmath doesn't know about `\textup`.  What does it do?

**Comment by Zmuogs** [comment]
`\textup` should apply "upright letters" formmating for that symbol.
I found that `\mathrm` does the job and PanDoc have no complains about it.

**Comment by jgm** [comment]
We can add support for `\textup`,but it should be a different issue.
