### ISSUE TITLE
Truncated trigonometric function names when convertin .tex -> .odt

### ISSUE THREAD

**Issue by Zmuogs** [jgm/texmath#148]
When converting from _LaTeX_ to _LibreOffice Writer_: resulting _.odt_ displays only first letter of trigonometric functions.
 For example: when converting [a.tex.zip](https://github.com/jgm/texmath/files/3908071/a.tex.zip)  file
```
\documentclass{article}
\usepackage{amsmath}
\usepackage{breqn}
\begin{document}
    \begin{dmath}
        x_{1} = l_{1} \sin{\left (\theta_{1}{\left (t \right )} \right )}
    \end{dmath}
\end{document}
```
using command
`pandoc -f latex -t odt -o a.odt a.tex`
and opening [a.odt.zip](https://github.com/jgm/texmath/files/3908072/a.odt.zip)  file I get
![Auto Generated Inline Image 1](https://user-images.githubusercontent.com/20404470/69912626-8aef1280-1434-11ea-9a30-c5a75797fc14.png)
 But pdflatex produces correct result
![Auto Generated Inline Image 2](https://user-images.githubusercontent.com/20404470/69912630-9e9a7900-1434-11ea-8e01-bd27b1655d8e.png)
I using Linux (Kubuntu 19.10) and `pandoc -v`:
```
pandoc 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
```
LibreOffice:
```
Version: 6.3.3.2
Build ID: 1:6.3.3-0ubuntu0.19.10.1
CPU threads: 16; OS: Linux 5.3; UI render: default; VCL: kde5;
Locale: lt-LT (lt_LT.UTF-8); UI-Language: en-US
Calc: threaded
```

**Comment by jgm** [comment]
The issue seems to be that texmath produces `<mo>sin</mo>`.  Since the MathML docs include explicit examples of mo elements with more than one character, this truncation behavior looks like a bug in LibreOffice.  However, there's a question raised on the mailing list whether texmath should use `<mi>` instead.

**Comment by jgm** [comment]
When you open the ODT in Word, it displays correctly. More reason to think it's a LibreOffice bug.
I suggest reporting it there.
