### ISSUE TITLE
SOME Math Symbols are not translated *FROM* .docx INTO Latex

### ISSUE THREAD

**Issue by DocxToLatexMathIssues** [jgm/texmath#153]
** I DO have examined the similar posts. No one applies ** 
[PandocTests.zip](https://github.com/jgm/pandoc/files/4197501/PandocTests.zip)

First of all let me thank you all for sharing the "Pandoc" tools with the rest of us.
Hoping to make something helpful I am taking the liberty to post this note in order to signal some issues I had in translating some very basic formulas *from* word to [Xe]LaTex.[XeLatex is required in order to handle Greek letters and other symbols]

I am aware that the sw is shared as-is and I thank you again for doing it.

At any rate I have tried "Pandoc" on several different platforms,
OSes and windows versions with general success, even with very complex articles with foot notes, pictures, and structures.
Nevertheless some of the following very simple situations still do not translate properly if at all.

I have done some extended tests but I think the following will be sufficient in order to understand what's going on.

 Batch Command used 
for %%a IN (%1) DO (
pandoc -s --extract-media="%%~dpaMyMedia" "%%~dpa%%~na%%~xa" -o "%%~dpa%%~na.tex"
)

The following are examples which DO work (just in order to check everything else is okay, compiler, encoding, etc.)

 - t00w
 - t03w
 - t04w
 - t05w

these are the one wich does NOT work (as expected):

 - t07N everyting *seems* OK. (those particular)Accents and DOUBLE Accents included

THOUGH the *"ARROW"* (with a LETTER on Top) does not translate at all (when together with a "letter on top. Pls see T09 and T10 for SIMPLE Arrow)

... trying to focus better..

 - t08N 
       a) the ACCENT on the FIRST B (DOUBLE LINE) does NOT show up in latex/pdf
	   b) the ARROW with a letter on top seems to be a problem here too
	   c) the culprit might NOT be the letter "R", which is rendered correcty otherwise
	   d) neither does the accent on D show up
	   
- t09N
		The "ARROW" (with a LETTER or anything on Top) does not translate at all 
                (it does as  SIMPLE Arrow though)
- t10N
		just for completeness SOME charachters like "intersection symbol" do not show up 
                when in simple text (i.e. not in a formula)
		

I am available for any help and or clarification you might need.

Thank you again for this wonderful set of tools.

**Comment by jgm** [comment]
```
% texmath -f omml -t native
<m:oMath>
             <m:groupChr>
                <m:groupChrPr>
                  <m:chr m:val="→" />
                  <m:vertJc m:val="bot" />
                  <m:ctrlPr>
                    <w:rPr>
                      <w:rFonts w:ascii="Cambria Math"
                      w:hAnsi="Cambria Math" />
                      <w:i />
                    </w:rPr>
                  </m:ctrlPr>
                </m:groupChrPr>
</m:oMath>
^D
[]
```

**Comment by jgm** [comment]
I've made some progress; now that second example is coming out as
```
$A\overset{\text{yields}}{\rightarrow}B$
```
which isn't quite right (arrow not long enough, text not italics). But much better!

We need to add some tests for these cases and improve it further.

**Comment by jgm** [comment]
Here are the differences after running your tests with a version of pandoc compiled against the latest version of this library:
```
--- t07N/t07N.tex	2020-02-13 10:06:00.000000000 -0800
+++ t07N/t07N.new.tex	2020-02-15 09:18:28.000000000 -0800
@@ -53,7 +53,7 @@

 \[\widetilde{\bar{X}} = S(f(X)) = S(\bar{X})\]

-\[\bar{D}\widetilde{\bar{D}}\]
+\[\bar{D}\overset{\quad S\quad}{\rightarrow}\widetilde{\bar{D}}\]

 \[\Sigma \cap \bar{D}\]

--- t08N/t08N.tex	2020-02-13 10:06:08.000000000 -0800
+++ t08N/t08N.new.tex	2020-02-15 09:18:29.000000000 -0800
@@ -57,7 +57,7 @@

 \[\mathbb{A = P}\]

-\[\Gamma\overset{̑}{D}\]
+\[\Gamma\overset{\quad\mathfrak{R}\quad}{\rightarrow}\overset{̑}{D}\]

 \[\overset{̑}{D} \subset \mspace{6mu}\Gamma\]

--- t09N/t09N.tex	2020-02-13 10:06:14.000000000 -0800
+++ t09N/t09N.new.tex	2020-02-15 09:18:29.000000000 -0800
@@ -53,10 +53,10 @@

 \[A \rightarrow B\]

-\[AB\]
+\[A\overset{\text{yields}}{\rightarrow}B\]

-\[AB\]
+\[A\overset{\mathrm{\Delta}}{\rightarrow}B\]
```
I suspect this fixes all the issues, but let me know if not.

**Comment by DocxToLatexMathIssues** [comment]
> Here are the differences after running your tests with a version of pandoc compiled against the latest version of this library:
> 
> ```
> --- t07N/t07N.tex	2020-02-13 10:06:00.000000000 -0800
> +++ t07N/t07N.new.tex	2020-02-15 09:18:28.000000000 -0800
> @@ -53,7 +53,7 @@
> 
>  \[\widetilde{\bar{X}} = S(f(X)) = S(\bar{X})\]
> 
> -\[\bar{D}\widetilde{\bar{D}}\]
> +\[\bar{D}\overset{\quad S\quad}{\rightarrow}\widetilde{\bar{D}}\]
> 
>  \[\Sigma \cap \bar{D}\]
> 
> --- t08N/t08N.tex	2020-02-13 10:06:08.000000000 -0800
> +++ t08N/t08N.new.tex	2020-02-15 09:18:29.000000000 -0800
> @@ -57,7 +57,7 @@
> 
>  \[\mathbb{A = P}\]
> 
> -\[\Gamma\overset{̑}{D}\]
> +\[\Gamma\overset{\quad\mathfrak{R}\quad}{\rightarrow}\overset{̑}{D}\]
> 
>  \[\overset{̑}{D} \subset \mspace{6mu}\Gamma\]
> 
> --- t09N/t09N.tex	2020-02-13 10:06:14.000000000 -0800
> +++ t09N/t09N.new.tex	2020-02-15 09:18:29.000000000 -0800
> @@ -53,10 +53,10 @@
> 
>  \[A \rightarrow B\]
> 
> -\[AB\]
> +\[A\overset{\text{yields}}{\rightarrow}B\]
> 
> -\[AB\]
> +\[A\overset{\mathrm{\Delta}}{\rightarrow}B\]
> ```
> 
> I suspect this fixes all the issues that are not simply issues with the font you're using, but let me know if not.


Thank you for your efforts and for working over the weekend.

All Your new lines 

```
--- t07N/t07N.tex	2020-02-13 10:06:00.000000000 -0800
+++ t07N/t07N.new.tex	2020-02-15 09:18:28.000000000 -0800
@@ -53,7 +53,7 @@

 \[\widetilde{\bar{X}} = S(f(X)) = S(\bar{X})\]

-\[\bar{D}\widetilde{\bar{D}}\]
+\[\bar{D}\overset{\quad S\quad}{\rightarrow}\widetilde{\bar{D}}\]

 \[\Sigma \cap \bar{D}\]

--- t08N/t08N.tex	2020-02-13 10:06:08.000000000 -0800
+++ t08N/t08N.new.tex	2020-02-15 09:18:29.000000000 -0800
@@ -57,7 +57,7 @@

 \[\mathbb{A = P}\]

-\[\Gamma\overset{?}{D}\]
+\[\Gamma\overset{\quad\mathfrak{R}\quad}{\rightarrow}\overset{?}{D}\]

 \[\overset{?}{D} \subset \mspace{6mu}\Gamma\]

--- t09N/t09N.tex	2020-02-13 10:06:14.000000000 -0800
+++ t09N/t09N.new.tex	2020-02-15 09:18:29.000000000 -0800
@@ -53,10 +53,10 @@

 \[A \rightarrow B\]

-\[AB\]
+\[A\overset{\text{yields}}{\rightarrow}B\]

-\[AB\]
+\[A\overset{\mathrm{\Delta}}{\rightarrow}B\]
```

(Copied and pasted directly into an old pandoc output)
compile nicely on my Miktex i.e. :

  

a- On XeLaTeX i.e. ("Process exited normally")
[Xelatex.zip](https://github.com/jgm/texmath/files/4210445/Xelatex.zip)

b- on pdflatex (and on Lyx 2011) i.e. ("Process exited normally")
[pdflatex.zip](https://github.com/jgm/texmath/files/4210446/pdflatex.zip)
*though w/ some font issues (regarding the encoding of  a char with I had to edit manually, and most likely due to the copy and paste process itself*

__Nevertheless On XeLaTeX the Greek letter "Delta" is not showing in pdf__.
Actually On XeLaTeX It does show in pdf __if__ is "isolated" such as in
```
  \[{\Delta}\]
```
Have not tried on LuaLaTex because I have general problems in compiling anything on LuaLaTex and I am sure is my fault.

At any rate

__it will be useful to have a "beta" executable with the new fixes in order to check from directly .docx what happens.__

Thank you again.

Thank you again.

**Comment by jgm** [comment]
You can try with pandoc 2.9.2, released today.

**Comment by jgm** [comment]
What is the context (i.e. the generated LaTeX) where `\Delta` doesn't show up?

**Comment by DocxToLatexMathIssues** [comment]
> What is the context (i.e. the generated LaTeX) where `\Delta` doesn't show up?
it does work in *BOTH* pdflatex *AND* XeLatex:
 `\[{\Delta}\]`
does _NOT_ work _just_ in XeLateX (it does still work in pdflalex though):
 `\[A\overset{\mathrm{\Delta}}{\rightarrow}B\] `


I am trying with with pandoc 2.9.2 and let you know
asap

**Comment by DocxToLatexMathIssues** [comment]
Hoping this will help others I am hiving some suggestionsthat could speed-up the use of such a useful software:
1- In the attached .zib there is my .bat batch file which I have been using
[AnyFormat_To_Latex.zip](https://github.com/jgm/texmath/files/4212649/AnyFormat_To_Latex.zip)
2- once pandoc.exe is in your PATH (pls check with command "where pandoc" that the path is the one you meant i.e. version etc.) the batch will work as described in the batch itself
3- *last but not least* dropping your .docx onto the batch entry on windows explorer (or any other "explorer" will produce the relevant .tex file. I hope this will promote the use of pandoc among the ones who object that it is "a command line only".
3-1- you can make a link to the batch file and copy that link anywhere you might find convenient.
On a separate comment I am posting the results obtained with the last 9.2.2 version.
ps Moderator feel free to move the present comment anywhere you might find appropriate.

**Comment by DocxToLatexMathIssues** [comment]
[292.zip](https://github.com/jgm/texmath/files/4212860/292.zip)
In the above you will find the tests with the new 2.9.2 version of pandoc.
They are self explanatory I am obviously available for any clarification you might need.
They have been carried on with the compiler/wysywig indicated in the relevant directory name.
Conclusion:

__The 9.2.2 translate great even on very complex papers (not attached)__

thank you so much.

In the following some residual issues.


t07N - okay on all "standard" compilers and on wysyswig Bakoma (issues on lyx and TexMacs but these are common and unrelated to the quality of the translation)

t08N - issues only on 

`\[\overline{A} \sim \overset{̿}{B}\]`

which by the way works on Lyx. This should not be a surprise because Lyx makes some processing that other do not make.
My sensation is that the above and any residual issues are now related to 
a- char codification (see the error message on bakoma)
b- and/or to fonts (see the automated succesful font substitution by Lyx)



t09N - issues only on 

`\[A\overset{\mathrm{\Delta}}{\rightarrow}B\]`

which by the way works on Lyx and on Bakoma and pdflatex. 

Feel free to close the comment anytime you find appropriate and I am available for starting from scratch as far as the residual very minor issues are concerned.


> 
> 
> > What is the context (i.e. the generated LaTeX) where `\Delta` doesn't show up?
> > it does work in _BOTH_ pdflatex _AND_ XeLatex:
> > `\[{\Delta}\]`
> > does _NOT_ work _just_ in XeLateX (it does still work in pdflalex though):
> > `\[A\overset{\mathrm{\Delta}}{\rightarrow}B\] `
> 
> I am trying with with pandoc 2.9.2 and let you know
> asap

**Comment by jgm** [comment]
So to summarize, in t08N with xelatex (the only one I really care about), we have two problems:

- missing double bar over B in first equation `\[\overline{A} \sim \overset{̿}{B}\]`
- missing curvy hat over D in last equation `\[\overset{̑}{D} \subset \mspace{6mu}\Gamma\]`

In t09N

- Delta missing over the arrow in third equation `\[A\overset{\mathrm{\Delta}}{\rightarrow}B\]`

**Comment by jgm** [comment]
I've fixed the double line accent issue.  I don't see a way to fix the second issue short of finding a font with that glyph.  The third issue can be worked around in the way I describe.
