### ISSUE TITLE
"\LaTeX"\"\TeX" not supported

### ISSUE THREAD

**Issue by gwern** [jgm/texmath#154]
Currently texmath appears to not support `$\TeX$` or `$\LaTeX$`, I noticed after trying to properly typeset the names of TeX & LaTeX while documenting my tech stack on `gwern.net`. It'd be nice to be able to discuss the typesetting in the Objectively Correct™ fashion.

On a side note: the texmath README doesn't explain what the scope of texmath is, or what is appropriate to request. Is supporting common constructs like `$\LaTeX$` what texmath is supposed to do? If one would expect to type something into a standard LaTeX installation without any special libraries imported and that thing doesn't work, would that be considered a bug?

**Comment by jgm** [comment]
texmath is for converting tex *math*, not arbitrary tex.  `\LaTeX` and `\TeX` are not commands that work in math mode, and if you create a tex document with `$\TeX$`, you'll find it causes an error.

If you're using pandoc, you should just be able to do `\LaTeX` (without the `$`) and it will be parsed as raw LaTeX inline.  Of course, this won't appear in HTML, but you could use a filter to replace this inline with something appropriate.

**Comment by gwern** [comment]
> texmath is for converting tex math, not arbitrary tex.

It would be good if the README could document what is considered in scope as 'math' and what is 'not math', then.

>  if you create a tex document with $\TeX$, you'll find it causes an error.

[Mathjax](https://github.com/jupyter/nbconvert/issues/262) apparently supports it, [Codecogs](https://www.codecogs.com/latex/eqneditor.php) renders them, and when I try it in LaTeX Base, it has no problem with them either: 
![Screenshot_2020-02-20 LaTeX Base Online LaTeX Editor and Compiler](https://user-images.githubusercontent.com/352559/74966569-434da680-53e5-11ea-863b-d4f506af8805.png)

**Comment by jgm** [comment]
Yes, `\LaTeX` by itself is fine.  But it's not okay in *math mode*, so `$\LaTeX$` causes an error (with real tex anyway, not sure about third-party tools).  There's a fundamental distinction between math mode and text mode in LaTeX.  `\emph{Hi}`, for example, is not math, and neither is `\LaTeX`.
