### ISSUE TITLE
MathML markup for hypergeometric function is mishandled

### ISSUE THREAD

**Issue by nelsonbeebe** [jgm/texmath#158]
For pandoc 2.10.1 (installed yesterday from git repo), I find
```
% pandoc -f html -t latex < bug.1
{ hypergeometric function { F23 } }
```
The input file is cut out of the HTML page for an article in the Journal of Number
Theory: https://doi.org/10.1016/j.jnt.2015.01.013

The input snippet is:
```
% cat bug.1
<SPAN CLASS="js-article-title">
  hypergeometric function
  <MATH xmlns:MML="http://www.w3.org/1998/Math/MathML" ALTIMG="si1.gif" OVERFLOW="scroll" CLASS="math">
    <MMULTISCRIPTS><MROW><MI>F</MI></MROW><MROW><MN>2</MN></MROW><NONE></NONE><MPRESCRIPTS></MPRESCRIPTS><MROW><MN>3</MN></MROW><NONE></NONE></MMULTISCRIPTS>
  </MATH>
</SPAN>
```
The expected LaTeX output should have `$_2F_3$`, with the 2 appearing BEFORE
the F.

**Comment by jgm** [comment]
Documentation for multiscripts:
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mmultiscripts

Also we should make element recognition case-insensitive, if indeed capitalized ones are legal.

**Comment by jgm** [comment]
See #100
