### ISSUE TITLE
LaTeX -> docx: pmod

### ISSUE THREAD

**Issue by catap** [jgm/texmath#160]
I'm trying to convert some `.tex` to `.docx` with a lot of complex math and `pandoc-2.11.3.1` can't convert `\pmod{4}` and similar cases.

Usual error looks like:
```
[WARNING] Could not convert TeX math 'x \equiv 3 \pmod{4}', rendering as TeX:
  x \equiv 3 \pmod{4}
                  ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```

Test case:
```
\documentclass{scrartcl}

\begin{document}

$x \equiv 3 \pmod{4}$

\end{document}
```

**Comment by catap** [comment]
@jgm `$x \equiv 3 \pmod{4}$` renders something like `x ≡ 3 (mod 4)`.

You can read details about different way to render mod here: https://vmuthu.livejournal.com/3054.html

**Comment by catap** [comment]
@jgm any plans to release the new version of pandoc with this commits in near future? :)

I'm asking because it isn't trivial to build it on macOS 11 because stack doesn't work and the easy way to install the new pandoc is using installer from the site.

**Comment by jgm** [comment]
Have you tried building with cabal?

**Comment by catap** [comment]
@jgm unfortunately I can't install nor stack nor cabal to macOS Big Sur :(

**Comment by jgm** [comment]
I don't know when I'll do a pandoc release, but I do plan to release a new version of texmath soon, and update pandoc to use it.  When that happens you should be able to grab a nightly, which I imagine will work for you.

**Comment by catap** [comment]
@jgm nevermind, I created an environment that works very well.

Thanks!
