### ISSUE TITLE
LaTeX -> docx: amsmath's cross-references

### ISSUE THREAD

**Issue by catap** [jgm/texmath#162]
I'm trying to convert some `.tex` to `.docx` with a lot of complex math and `pandoc-2.11.3.1` and it can't convert cross references for equation when I use amsmath's tag.

Usual error looks like:
```
WARNING] Could not convert TeX math 'x = y \tag{\ref{eq:x}}', rendering as TeX:
  x = y \tag{\ref{eq:x}}
            ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```

Test case:
```
\documentclass{scrartcl}

\usepackage{amsmath}

\begin{document}

\begin{equation}\label{eq:x}
  x = y
\end{equation}

\begin{equation*}
  x = y \tag{\ref{eq:x}}
\end{equation*}


\end{document}
```

**Comment by catap** [comment]
@jgm any plans to support it in near future?

**Comment by jgm** [comment]
In the near future, no.

**Comment by catap** [comment]
as far as I can see `pandoc` never tracks equation, so, by any chance any easy way can you suggest a way how I can force `pandoc` to ignore `\tag{..}`?

**Comment by catap** [comment]
nevermind.
```
\newcommand{\tag}[1]{}
```

makes the trick.
