### ISSUE TITLE
amsmath's genfrac

### ISSUE THREAD

**Issue by catap** [jgm/texmath#164]
`\genfrac` is very common and easy way to create complex fractions.

For example:
```
\genfrac(]{0pt}{2}{a+b}{c+d}
```

allows to create
<img width="205" alt="Screenshot 2020-12-27 at 12 48 57" src="https://user-images.githubusercontent.com/37775/103170095-e6f7b680-4841-11eb-8361-536da39797be.png">

Right now it doesn't supported. Is it possible to add?

The test-case:
```
\documentclass[a4paper]{article}
\usepackage{amsmath}

\begin{document}

\begin{equation*}
\genfrac(]{0pt}{2}{a+b}{c+d}
\end{equation*}

\end{document}
```

**Comment by jgm** [comment]
It's supported but there are bugs in the implementation.
I will fix.
