### ISSUE TITLE
Complex formula

### ISSUE THREAD

**Issue by nzgwynn** [jgm/texmath#174]
This latex coding was not processed in the word format:

\begin{eqnarray*}
 d_j = \frac{| \sum_{i = 1}^{\frac{m}{2}}C_{ij}^T - \sum_{i = 1}^{\frac{m}{2}}C_{ij}^C |}{\frac{m}{2}} 
\end{eqnarray*}

Neither was:

\begin{eqnarray*}
 v_{ij}^* = \prod_{i=1}^{m} v_{ij} \times s_j
\end{eqnarray*}

**Comment by jgm** [comment]
With latest pandoc I cannot reproduce the issue:
```
% pandoc -o my.docx
$$
\begin{eqnarray*}
d_j = \frac{| \sum_{i = 1}^{\frac{m}{2}}C_{ij}^T - \sum_{i = 1}^{\frac{m}{2}}C_{ij}^C |}{\frac{m}{2}}
\end{eqnarray*}
$$

$$
\begin{eqnarray*}
v_{ij}^* = \prod_{i=1}^{m} v_{ij} \times s_j
\end{eqnarray*}
$$
^D
```
<img width="281" alt="Screen Shot 2021-04-21 at 10 50 20 PM" src="https://user-images.githubusercontent.com/3044/115662604-10a68300-a2f4-11eb-97fb-c703360cb3d8.png">
