### ISSUE TITLE
Support \dotsc \dotsb \dotsm \dotsi \dotso from amsmath

### ISSUE THREAD

**Issue by stoianmihail** [jgm/texmath#179]
Hi!

When converting from Latex to Word, I get the following warning on this input `$\{1, 2, \dotsc, i - 1\}$`:

`pandoc -s main.tex --bibliography=sample.bib -o work_document.docx`
`[WARNING] Could not convert TeX math '\{1, 2, \dotsc, i - 1\}', rendering as TeX:`
  `\{1, 2, \dotsc, i - 1\}`
                     `^ # pointing to comma`
  `unexpected control sequence \dotsc`
  `expecting "%", "\\label", "\\nonumber" or whitespace`

Pandoc:
`pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1`

OS:
`Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal`

In the output word, that part is rendered as is.
Let me know whether I can help with a quick fix.

Thanks!
Mihail

**Comment by jgm** [comment]
See https://tex.stackexchange.com/questions/122491/difference-of-the-dots
