### ISSUE TITLE
Underbar Items without m:pos disappear

### ISSUE THREAD

**Issue by Meimax** [jgm/texmath#187]
According to the specification of omml, a m:pos element defaults to "bot", if no value is given (https://standards.iso.org/ittf/PubliclyAvailableStandards/c071691_ISO_IEC_29500-1_2016.zip, 22.1.2.84):
> 22.1.2.84 pos (Position)
> This element specifies the position of the bar or group character in the parent object; the default is bot. 
> Whether the element is absent or present without the val attribute, the default of the val attribute is bot.

At the moment bar items (`m:bar`) without a `m:pos` element are set to `Nothing`, https://github.com/jgm/texmath/blob/d9013d8ef61660be937ed769438058c92f459397/src/Text/TeXMath/Readers/OMML.hs#L261 so they disappear.
Example: [Underbar.txt](https://github.com/jgm/texmath/files/8117321/Underbar.txt)
With `cat .\Underbar.txt | texmath --from=omml --to=tex`, the output is `= T = \overline{T}`, but the expected output would be either `\underbar{T} = T = \overline{T}` or `\underline{T} = T = \overline{T}` to match the word file.

Maybe a solution would be to just set the `bot` case as the default, changing
```c2hs
case pos of
    "top" -> Just [EOver False baseExp (ESymbol TOver "\773")]
    "bot" -> Just [EUnder False baseExp (ESymbol TUnder "\818")]
    _     -> Nothing
```
to
``` c2hs
case pos of
   "top" -> Just [EOver False baseExp (ESymbol TOver "\773")]
    _ -> Just [EUnder False baseExp (ESymbol TUnder "\818")] 
```

**Comment by Meimax** [comment]
This pull request didn't fully fix the issue. If the m:pos element is not there, it currently still deletes the baseExp:
``` xml
 <m:bar>
    <m:barPr>
	<m:pos m:val=""/>
      <m:ctrlPr>
      </m:ctrlPr>
    </m:barPr>
    <m:e>
      <m:r>
        <m:t>T</m:t>
      </m:r>
    </m:e>
  </m:bar>
```
this evaluates correctly, but if you delete either only the val attribute or the pos element:
``` xml
<m:bar>
    <m:barPr>
	<m:pos/> <-- or without this line -->
      <m:ctrlPr>
      </m:ctrlPr>
    </m:barPr>
    <m:e>
      <m:r>
        <m:t>T</m:t>
      </m:r>
    </m:e>
  </m:bar>
```
the expression is not there at all.

**Comment by jgm** [comment]
I just pushed a change that I think will fix this.  If you can test, that would be great.  This change allows m:pos to be missing or to have an empty attribute.  In fact it allows the whole bar:Pr element to be missing.

**Comment by Meimax** [comment]
It works in all of these cases. Thank you.

**Comment by BBreiden** [comment]
Thank you for this fix! Is this change already included in the latest pandoc?

**Comment by jgm** [comment]
No, it will be in the next release; for now you could try a nightly.
