### ISSUE TITLE
Stack installing failed

### ISSUE THREAD

**Issue by buaalyx** [jgm/texmath#192]
I'm writing my paper, I want to convert my equations in .doc to latex formulas.
But the "mathml to tex" service here https://johnmacfarlane.net/texmath   is unavailable.
So I tried to install texmath with stack, I installed stack successfully but when I run  
`stack install --flag texmath:executable`
or
`stack install --flag texmath:server`
I got the following error message 
```
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```
I'm new in haskell, the version of stack is the newest, so I really don't know how to fix it

**Comment by jgm** [comment]
Try
```
stack install --flag texmath:executable texmath
```
If you don't provide the package name as an argument, it will only work if you run stack in the root of this source repository.

**Comment by jgm** [comment]
Thanks for alerting me to the server issue. The server seems to die periodically for reasons that aren't clear to me.

**Comment by jgm** [comment]
I think the server issue is fixed.
Closing.
