### ISSUE TITLE
"aligned" should be used instead of some "matrix" when converting to latex

### ISSUE THREAD

**Issue by ZhuangQu** [jgm/texmath#196]
[demo.docx](https://github.com/jgm/pandoc/files/8493796/demo.docx)
Execute the command: `pandoc demo.docx -o demo.tex`
The formula in word
`f(x)={█(x&=1 & y&=2@xxx&=111 & yyy&=222)┤`
is converted to
```
\[
	f(x) = \left\{
		\begin{matrix}
			x\& = 1\ \&\ y\& = 2 \\
			xxx\& = 111\ \&\ yyy\& = 222 \\
		\end{matrix} 
	\right.
\]
```
which is wrong. The correct conversion is 
```
\[
	f(x) = \left\{
		\begin{aligned}
			x& = 1\ &\ y& = 2 \\
			xxx& = 111\ &\ yyy& = 222 \\
		\end{aligned} 
	\right.
\]
```

**Comment by jgm** [comment]
Changing this to produce `aligned` would require changes in the underlying types. We don't have a constructor that corresponds to the align environment, so we fall back on array which should give similar results.  What I can do is fix the bug that produces the `&` symbols, and ensure that they instead split the formula into columns.

**Comment by jgm** [comment]
Output with my changes:
```tex
f(x) = \left\{ \begin{array}{rlll}
x & = 1\  & \ y & = 2 \\
xxx & = 111\  & \ yyy & = 222 \\
\end{array} \right.\ 
```
which is certainly much better.

**Comment by jgm** [comment]
rendered using tex:

<img width="381" alt="Screen Shot 2022-10-08 at 12 44 03 PM" src="https://user-images.githubusercontent.com/3044/194724741-af90da06-b2b2-4cfd-be4f-304a451ba20b.png">

**Comment by jgm** [comment]
Ah wait, I forgot that the TeX writer already renders certain arrays as "aligned" by default.
So we can get
```tex
f(x) = \left\{ \begin{aligned}
x & = 1\  & \ y & = 2 \\
xxx & = 111\  & \ yyy & = 222 \\
\end{aligned} \right.\
```
after all.
