### ISSUE TITLE
Do not use extra lr in typst writer

### ISSUE THREAD

**Issue by istudyatuni** [jgm/texmath#233]
texmath inserts `lr` for every parentheses it found, though parentheses are scaled automatically. I think it would be good to not write these extra `lr`

**Comment by istudyatuni** [comment]
I noticed in tests that somewhere `\(..\)` is written, I'm probably missing something here?

**Comment by jgm** [comment]
You're right that we use `lr` more than strictly needed. We use it to render any EDelimited element.  I think we could omit the `lr` when the delimiters are a matched pair `()` `[]` or `{}` and there is no middle delimiter of the same sort...
