### ISSUE TITLE
Writing primes ′ in Typst

### ISSUE THREAD

**Issue by njericha** [jgm/texmath#239]
Currently, converting TeX/markdown `$f'_n$` to Typst gives `$f prime_n$`. This is rendered incorrectly with added space as:
![image](https://github.com/user-attachments/assets/a304d088-62fe-4293-af5a-42e11d184ef8)

I don't think any special conversion is necessary since `$f'_n$` produces the correct output in Typst:
![image](https://github.com/user-attachments/assets/0c7c967d-f010-4938-9367-8952f48eee3f)
`$f^'_n$` and `$f^prime_n$` are also correct Typst inputs. `$f prime_n$` reads as `f`, followed by a subscripted prime `'_n`, rather than subscripting `f`.

Also, multiple primes `$f''$`, `$f'''$`, `$f''''$` are converted to Typst `$f prime.double$`, `$f prime.triple$`, `$f prime.quad$`, but adding more than 4 causes an unnatural break: `$f'''''$` is converted to `$f prime.quad prime$` and rendered as 
![image](https://github.com/user-attachments/assets/ef51c508-9929-4c19-abd2-d1ce3a1db5f8)

The Typst inputs `$f'''''$`, `$f^'''''$` and `$f^prime(#5)$` produce the correct output
![image](https://github.com/user-attachments/assets/eec52101-4b82-4ae7-aacf-cc3559a7d369)

See https://typst.app/docs/reference/math/primes/

**Comment by jgm** [comment]
First let's check what the tex reader does:
```
f'_n
[ EIdentifier "f"
, ESub (ESymbol Ord "\8242") (EIdentifier "n") ]
f''_n
[ EIdentifier "f"
, ESub (ESymbol Ord "\8243") (EIdentifier "n") ]
f'''_n
[ EIdentifier "f"
, ESub (ESymbol Ord "\8244") (EIdentifier "n") ]
f''''_n
[ EIdentifier "f"
, ESub (ESymbol Ord "\8279") (EIdentifier "n") ]
f'''''_n
[ EIdentifier "f"
, ESymbol Ord "\8279"
, ESub (ESymbol Ord "\8242") (EIdentifier "n") ]
```
So, for consecutive primes, different unicode multiprime characters are used -- I believe that gives better results in some output formats.  But for five primes something bad happens.

**Comment by jgm** [comment]
The typst writer simply looks up these symbols in the typst symbol table.  We should be able to work around that and have it substitute regular `'` characters, but we do need to do something about the five-prime case in the tex reader.

**Comment by jgm** [comment]
We also need to avoid that space after f.
That seems to be added by `writeExps`, which intercalates spaces.

**Comment by jgm** [comment]
We can make `writeExps` more selective, but:  when, exactly, are spaces *needed* in a typst math expression?  Certainly they are needed to separate two consecutive alphabetical strings; are there other cases?
