### ISSUE TITLE
OMML should write dPr in the order (begChr, sepChr, endChr), not (begChr, endChr, sepChr)

### ISSUE THREAD

**Issue by refashioned** [jgm/texmath#243]
When I generate a docx file containing math with Pandoc (v3.5) and open it in LibreOffice Writer (v7.4.7.2), every right-hand delimiters turns into right parenthesis, even when it could be something else, such as a square bracket or vertical bar. I tracked the problem down to the order in which TeXMath writes the subelements of the `dPr` element. TeXMath uses the order (`begChr`, `endChr`, `sepChr`), while LibreOffice is expecting (`begChr`, `sepChr`, `endChr`). The right parenthesis is a default fallback in the LibreOffice code.

This is the code in TeXMath that writes the elements in the order (`begChr`, `endChr`, `sepChr`):
https://github.com/jgm/texmath/blob/0.12.8.11/src/Text/TeXMath/Writers/OMML.hs#L209-L216
```
   EDelimited start end xs ->
                  [ mnode "d" $ mnode "dPr"
                               [ mnodeA "begChr" (T.unpack start) ()
                               , mnodeA "endChr" (T.unpack end) ()
                               , mnodeA "sepChr" (T.unpack sepchr) ()
                               , mnode "grow" () ]
                              : map (mnode "e" . concatMap (showExp props)) es
                  ]
```

This is the code in LibreOffice that expects the order (`begChr`, `sepChr`, `endChr`) and supplies `")"` as a default:
https://git.libreoffice.org/core/+/refs/tags/libreoffice-24.8.3.2/starmath/source/ooxmlimport.cxx#301
```
    OUString opening = u"("_ustr;
    OUString closing = u")"_ustr;
    OUString separator = u"|"_ustr;
    if( XmlStream::Tag dPr = m_rStream.checkOpeningTag( M_TOKEN( dPr )))
    {
        if( XmlStream::Tag begChr = m_rStream.checkOpeningTag( M_TOKEN( begChr )))
        {
            opening = begChr.attribute( M_TOKEN( val ), opening );
            m_rStream.ensureClosingTag( M_TOKEN( begChr ));
        }
        if( XmlStream::Tag sepChr = m_rStream.checkOpeningTag( M_TOKEN( sepChr )))
        {
            separator = sepChr.attribute( M_TOKEN( val ), separator );
            m_rStream.ensureClosingTag( M_TOKEN( sepChr ));
        }
        if( XmlStream::Tag endChr = m_rStream.checkOpeningTag( M_TOKEN( endChr )))
        {
            closing = endChr.attribute( M_TOKEN( val ), closing );
            m_rStream.ensureClosingTag( M_TOKEN( endChr ));
        }
        m_rStream.ensureClosingTag( M_TOKEN( dPr ));
    }
```

I'm not an expert at OMML or XML Schemas, but I found [this page](https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_dPr_topic_ID0EZAMZB.html) that puts the contents of `dPr` in a `sequence`, which I take to mean that `sepChr` should precede `endChr`:

```
<complexType name="CT_DPr">
	<sequence>
	<element name="begChr" type="CT_Char" minOccurs="0"/>
	<element name="sepChr" type="CT_Char" minOccurs="0"/>
	<element name="endChr" type="CT_Char" minOccurs="0"/>
	<element name="grow" type="CT_OnOff" minOccurs="0"/>
	<element name="shp" type="CT_Shp" minOccurs="0"/>
	<element name="ctrlPr" type="CT_CtrlPr" minOccurs="0"/>
	</sequence>
</complexType>
```

This is a small reproduction recipe:

```
echo '$|x| = \max[x, -x]$' | pandoc -t docx -o x.docx
```

In my LibreOffice Writer, it renders like this:

![|x)=max\[x,−x\]](https://github.com/user-attachments/assets/59f9dc09-7a11-4315-a031-aa02f72e6d8c)

When I double-click the formula, this is how it's serialized in the editor:

```
left lline x right ) = max left [x , − x right )
```

<details>
<summary>OMML output</summary>
<pre>
&lt;m:oMath&gt;
  &lt;m:d&gt;
    &lt;m:dPr&gt;
      &lt;m:begChr m:val="|" /&gt;
      &lt;m:endChr m:val="|" /&gt;
      &lt;m:sepChr m:val="" /&gt;
      &lt;m:grow /&gt;
    &lt;/m:dPr&gt;
    &lt;m:e&gt;
      &lt;m:r&gt;
        &lt;m:t&gt;x&lt;/m:t&gt;
      &lt;/m:r&gt;
    &lt;/m:e&gt;
  &lt;/m:d&gt;
  &lt;m:r&gt;
    &lt;m:rPr&gt;
      &lt;m:sty m:val="p" /&gt;
    &lt;/m:rPr&gt;
    &lt;m:t&gt;=&lt;/m:t&gt;
  &lt;/m:r&gt;
  &lt;m:r&gt;
    &lt;m:rPr&gt;
      &lt;m:sty m:val="p" /&gt;
    &lt;/m:rPr&gt;
    &lt;m:t&gt;max&lt;/m:t&gt;
  &lt;/m:r&gt;
  &lt;m:d&gt;
    &lt;m:dPr&gt;
      &lt;m:begChr m:val="[" /&gt;
      &lt;m:endChr m:val="]" /&gt;
      &lt;m:sepChr m:val="" /&gt;
      &lt;m:grow /&gt;
    &lt;/m:dPr&gt;
    &lt;m:e&gt;
      &lt;m:r&gt;
        &lt;m:t&gt;x&lt;/m:t&gt;
      &lt;/m:r&gt;
      &lt;m:r&gt;
        &lt;m:rPr&gt;
          &lt;m:sty m:val="p" /&gt;
        &lt;/m:rPr&gt;
        &lt;m:t&gt;,&lt;/m:t&gt;
      &lt;/m:r&gt;
      &lt;m:r&gt;
        &lt;m:rPr&gt;
          &lt;m:sty m:val="p" /&gt;
        &lt;/m:rPr&gt;
        &lt;m:t&gt;−&lt;/m:t&gt;
      &lt;/m:r&gt;
      &lt;m:r&gt;
        &lt;m:t&gt;x&lt;/m:t&gt;
      &lt;/m:r&gt;
    &lt;/m:e&gt;
  &lt;/m:d&gt;
&lt;/m:oMath&gt;
</pre>
</details>

If I hack word/document.xml inside the .docx file and swap the order of `endChr` and `sepChr`, then the delimiters render correctly.

**Comment by jgm** [comment]
Thanks for the excellent bug report!
