### ISSUE TITLE
Arguments flipped in OMML reader

### ISSUE THREAD

**Issue by mpickering** [jgm/texmath#66]
I think the arguments are the wrong way round somewhere in the OMML reader.

`pandoc -f tex -t omml | pandoc -f omml -t tex`
In:
`\overset{r}{\rightarrow}`
Out:
`\overset{\rightarrow}{r}`

**Comment by jgm** [comment]
@jkr did you ever come back to this?

**Comment by jgm** [comment]
The fix I recommended did fix mpickering's case.  I'll make this change and close this.
