### ISSUE TITLE
remove the ` -auto-all -caf-all` from .cabal files in all hackage release of texmath

### ISSUE THREAD

**Issue by cartazio** [jgm/texmath#72]
@jgm @mpickering  with your permission, i will use my trustee powers to make edits on all those release so that impact of the profiling blowup will be mitigated on all current releases that someone might use to build pandoc.

**Comment by jgm** [comment]
OK with me.  I plan to release a new version soon, though, so this might not be necessary.

**Comment by cartazio** [comment]
Gotcha.   I still think its a worth while change so folks trying to build
older versions of pandoc dont hit the blowup.  ...  Assuming there aren't
too many releases on hackage I'll do the edits this afternoon
