### ISSUE TITLE
Render amsmath symbols in mathml output

### ISSUE THREAD

**Issue by schmittlauch** [jgm/texmath#81]
I use pandoc to write notes during lectures and make heavy use of inline Tex math. While I use kokoi for live preview during editing, which produces html5 files including MathML formulas, the end result shall be saved as pdf using XeLaTex.
I encountered that math containing symbols from amsmath isn't redered to MathML.

Example:
`$5 \equiv 1 (\mod{2})$` where `\mod{}` is part of amsmath.

First, is it even possible to render amsmath symbols in MathML or doesn't MathML itself support it? Second, are there plans to support MathML output of amsmath in texmath?

Regards

**Comment by mpickering** [comment]
It is possible to render much more in MathML than is easily possible in
latex. It just needs someone to implement support for the "\mod" command.

**Comment by jgm** [comment]
I've implemented `\mod` and will close this.  If you encounter other missing things, please put up issues about them.  We'd like to cover as much of amsmath as feasible.

**Comment by schmittlauch** [comment]
thx
