### ISSUE TITLE
Overbrace does not appear in docx output

### ISSUE THREAD

**Issue by tazzben** [jgm/texmath#82]
The following LaTeX math does not render correct when converted through pandoc to docx:

`\begin{equation}
	\label{eq:num}
	\frac{\delta^2 u}{\delta D \delta t} = \overbrace{\overbrace{u_R(\cdot)}^{+}\overbrace{R_{Dt}(\cdot)}^{?}}^{A}+ \overbrace{\overbrace{R_t(\cdot)}^{+}(\overbrace{\overbrace{u_{RR}(\cdot)}^{-}\overbrace{R_D(\cdot)}^{-}}^{+}+ \overbrace{\overbrace{K'(D)}^{+}\overbrace{u_{KR}(\cdot)}^{+}}^{+})}^{B}
\end{equation}
`

The overbraces are missing, but the +/- signs do appear in the proper positions.  I was asked in the Google Groups to submit this issue here.

**Comment by jgm** [comment]
Let's try the simplest case.
```
pandoc -o my.docx
$$\overbrace{x+y}$$
```
Even here I don't see the overbrace.
`texmath -t omml` lets you see the omml produced by texmath:
``` xml
<m:oMathPara>
  <m:oMathParaPr>
    <m:jc m:val="center" />
  </m:oMathParaPr>
  <m:oMath>
    <m:acc>
      <m:accPr>
        <m:chr m:val="︷" />
      </m:accPr>
      <m:e>
        <m:r>
          <m:rPr />
          <m:t>x</m:t>
        </m:r>
        <m:r>
          <m:rPr />
          <m:t>+</m:t>
        </m:r>
        <m:r>
          <m:rPr />
          <m:t>y</m:t>
        </m:r>
      </m:e>
    </m:acc>
  </m:oMath>
</m:oMathPara>
```

I created the equation in Word and it produced:
``` xml
<m:oMathPara>
        <m:oMath>
          <m:groupChr>
            <m:groupChrPr>
              <m:chr m:val="⏞"/>
              <m:pos m:val="top"/>
              <m:vertJc m:val="bot"/>
              <m:ctrlPr>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
                  <w:i/>
                </w:rPr>
              </m:ctrlPr>
            </m:groupChrPr>
            <m:e>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
                </w:rPr>
                <m:t>x+y
                </m:t>
              </m:r>
            </m:e>
          </m:groupChr>
        </m:oMath>
</m:oMathPara>
```

**Comment by jgm** [comment]
Okay, I've determined that the problem is the character we're using for the overbrace.
We're using `︷`.  Changing this to `⏞` fixes things.
