### ISSUE TITLE
MathML rendering of align, etc. environments only aligns one equation per line

### ISSUE THREAD

**Issue by fatanassow** [jgm/texmath#84]
texmath's MathML output will only align the first two columns in something like this:

    $$\begin{align}
        a &= b & c &= d
    \end{align}$$

That is, it will only align the "a" and "b" columns. It ought to align "c" and "d" as well.

Expected behavior: `align` & friends allow multiple equations per line, and align each column around alternate ampersands, like AMSLaTeX does.

Here is the MML output (produced by Pandoc) of the snippet above:

    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <semantics>
        <mtable>
          <mtr>
            <mtd columnalign="right">
              <mi>a</mi>
            </mtd>
            <mtd columnalign="left">
              <mo>=</mo>
              <mi>b</mi>
            </mtd>
            <mtd>
              <mi>c</mi>
            </mtd>
            <mtd>
              <mo>=</mo>
              <mi>d</mi>
            </mtd>
          </mtr>
        </mtable>
        <annotation encoding="application/x-tex">\begin{align}     a &amp;= b &amp; c &amp;= d \end{align}</annotation>
      </semantics>
    </math>

I think the second two `mtd`'s (and any others) ought also to have `columnalign` attributes set.

Reference: https://groups.google.com/forum/#!topic/pandoc-discuss/faM55dIJDI0

**Comment by jgm** [comment]
+++ Frank Atanassow [Feb 07 16 11:06 ]:

>   I think the second two mtd's (and any others) ought also to have
>   columnalign attributes set

And what should their alignments be?  I confess I've never
used align with four columns.  Do we get another right and
left, or both left?

**Comment by fatanassow** [comment]
It should be right, left, right, left, right, left and so on.

Here is a larger example from ftp://ftp.ams.org/pub/tex/doc/amsmath/amsldoc.pdf

    \begin{align}
    x&=y & X&=Y & a&=b+c\\
    x’&=y’ & X’&=Y’ & a’&=b\\
    x+x’&=y+y’ & X+X’&=Y+Y’ & a’b&=c’b
    \end{align}

Similar considerations apply to `flalign`, `alignat` and maybe some others. `eqnarray` (is deprecated but) also supports multiple equations per line, I believe, although the format is different: right, center, left, right, center, left, ...
