### ISSUE TITLE
Writers/OMML: Short nary is loaded incorrectly in LibreOffice

### ISSUE THREAD

**Issue by xou** [jgm/texmath#88]
First off, apologies since this seems to be a bug in LibreOffice, but it's triggered by texmath's output format and has a relatively easy fix here.

The formula

    \sum_{i=1}^100 x = \frac{100*101}{2}

Is rendered incorrectly in LibreOffice
![Screenshot](http://bildungsresistenz.de/tmp.h/texmath-libreoffice.png)

Using x + 1 (in parentheses) renders to

![Screenshot](http://bildungsresistenz.de/tmp.h/texmath-libreoffice-plusone.png)

The formula is rendered correctly when opened in MS Office.

TexMath generates the following XML:

```xml
    <m:nary>
      <m:naryPr>
        <m:chr m:val="∑" />
        <m:limLoc m:val="undOvr" />
        <m:subHide m:val="off" />
        <m:supHide m:val="off" />
      </m:naryPr>
      <m:e>
        <m:r>
          <m:rPr />
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:sub>
(i = 1)
      </m:sub>
      <m:sup>
(100)
      </m:sup>
    </m:nary>
```

LibreOffice seems to expect the `<m:e>` part to appear *after* the `<m:sub>` and `<m:sup>` part, changing the order makes the formula render correctly:

```xml
    <m:nary>
      <m:naryPr>
        <m:chr m:val="∑" />
...
      </m:naryPr>
      <m:sub>
(i = 1)
      </m:sub>
      <m:sup>
(100)
      </m:sup>
      <m:e>
        <m:r>
          <m:rPr />
          <m:t>x</m:t>
        </m:r>
      </m:e>
    </m:nary>
```

![Screenshot](http://bildungsresistenz.de/tmp.h/texmath-libreoffice-fixed.png)

Again, this seems to be a bug in LibreOffice, but the change required in texmath is relatively straightforward:

```patch
--- a/src/Text/TeXMath/Writers/OMML.hs
+++ b/src/Text/TeXMath/Writers/OMML.hs
@@ -223,7 +223,7 @@ makeNary props t s y z w =
                  , mnodeA "supHide"
                     (if z == EGrouped [] then "on" else "off") ()
                  ]
-               , mnode "e" $ showExp props w
                , mnode "sub" $ showExp props y
-               , mnode "sup" $ showExp props z ]
+               , mnode "sup" $ showExp props z
+               , mnode "e" $ showExp props w]
```

This breaks the testcases of course, but I can have a look at them & submit a pull request if you like.

Cheers,

Niko

**Comment by jgm** [comment]
I don't mind this change if you want to submit a PR,
including tests, but have you submitted a bug report to LibreOffice?

+++ Nikolai Weh [Mar 22 16 21:39 ]:

**Comment by xou** [comment]
Thanks, I've created pull request #89.

I've had a look at the OMML spec (4th edition, part 1, retrieved from [here](http://www.ecma-international.org/publications/standards/Ecma-376.htm)). While MS Word renders the formula correctly, the spec (excerpt below) actually requires the elements to be in the order `naryPr, sub, sup, e`, so it doesn't seem to be a LibreOffice bug.

```xml
<xsd:complexType name="CT_Nary">
  <xsd:sequence>
    <xsd:element name="naryPr" type="CT_NaryPr" minOccurs="0"/>
    <xsd:element name="sub" type="CT_OMathArg"/>
    <xsd:element name="sup" type="CT_OMathArg"/>
    <xsd:element name="e" type="CT_OMathArg"/>
  </xsd:sequence>
</xsd:complexType>
```

An extended version is mirrored [here](https://github.com/t-yuki/ooxml-xsd/blob/master/shared-math.xsd#L952).

**Comment by jgm** [comment]
Great, that's really helpful. Thanks for the PR.

**Comment by jgm** [comment]
Since you've been looking at the OMML spec, may I ask
whether the same order requiremnets apply to sSub, sSup,
sSubSup, limLow, limUpp, and perhaps other elements where
texmath currently puts the e before the sub and/or sup?


+++ Nikolai Weh [Mar 24 16 05:32 ]:

**Comment by xou** [comment]
For sSub, sSup, sSubSup, limLow and limUpp the `*Pr` element is directly followed by the `e` element, TexMath is correct here. I did check a couple of others elements against the XSD, and I couldn't find any further problems.

If I find the time, i'll see if there is a way of automatically verifying the generated omml files against the XSD, potentially as part of the `cabal test` run.

**Comment by jgm** [comment]
Great, I've released a new version.
Validation would be welcome if you get around to it.
