### ISSUE TITLE
LaTeX parser fails on nested math environments when $$ is used

### ISSUE THREAD

**Issue by cazgp** [jgm/texmath#93]
This MWE compiles fine in latex.

```
\documentclass{article}

\begin{document}
$$
{\mbox{\boldmath $\theta $}}_2||^2
$$
\end{document}
```

However, pandoc fails when reading it:

```
$ pandoc -f latex problem.tex -o test.xml
pandoc: 
Error at "source" (line 5, column 33):
unexpected "^"
expecting "%", lf new-line, "\\", "{", "-", "``", "\8220", "\"`", "\"", "`", "\8216", "''", "\8221", "'", "\8217", "~", "$$", "$", "^^", "&" or \end{document}
{\mbox{\boldmath $\theta $}}_2||^2
```

If, however, the `$$` delimiters are changed to `\begin{displaymath}`, then it works fine.

(from https://github.com/jgm/pandoc/issues/3164)

**Comment by cazgp** [comment]
@jgm commented: This issue should really be in jgm/texmath, which handles math for pandoc. texmath doesn't handle well commands that act as "switches", like \boldmath. It likes commands with explicit arguments, such as \mathbf. This could be improved in future versions. Note that you should be able to do: \mbox{$\mathbf{\theta}$}_2||^2

**Comment by cazgp** [comment]
Unfortunately I don't have much control over the document other than that which can be done programmatically.

How come it works fine with \begin{displaymath}?

**Comment by jgm** [comment]
It works with `\begin{displaymath}` because in that case, pandoc parses the whole thing as raw LaTeX, rather than as a Math element.  (This doesn't matter if you're targeting LaTeX output, but if you are targeting DocBook, Word, etc., raw LaTeX won't be converted properly.)

**Comment by jgm** [comment]
OK, apparently

> An `\mbox` within math mode does not use the current math font; rather it uses the typeface of the surrounding running text.

so we need to handle this better.

**Comment by jgm** [comment]
As of commit 2f79e0c09c726b477a068f196ebfed227b19b1aa,

    {\mbox{$\mathbf{\theta}$}}_2||^2   

now works.  The original

    {\mbox{\boldmath $\theta $}}_2||^2

doesn't work, but that's because we don't support tex-style switches like `\boldmath`, not because of problems with nested math in mbox.
