### ISSUE TITLE
Speed up builds and remove cbits

### ISSUE THREAD

**Issue by jgm** [jgm/texmath#96]
GHC is very slow compiling modules with long literals, e.g. src/Text/TeXMath/Unicode/ToTeX.hs, especially with profiling enabled.  (And this seems worse with ghc 8.0.*.)

We're currently working around this with some modules by using the FFI (cbits/*.c).
However, this has the drawback that the module can't be compiled with ghcjs.

Thus it is worth exploring another approach, that used in skylighting: see jgm/skylighting#7 for background.

We'd like to avoid having any run-time penalty, but presumably this could be done with TH. (However, my attempts to do this with skylighting failed, for reasons I never completely understood -- the function to generate a Q Exp for a Data instance didn't seem to work in that case.)

See http://stackoverflow.com/questions/16348340/compiling-very-large-constants-with-ghc
and especially Alpaca's answer at http://stackoverflow.com/questions/12716215/load-pure-global-variable-from-file
Cf. Snoyman's answer at http://stackoverflow.com/questions/15721779/haskell-yaml-quasiquotation

Really what we need is a small library that implements quasiquotation to read a string representation of any instance of Data from a file at compile time.  Or does this exist already?
@cartazio

**Comment by jgm** [comment]
OK, it doesn't seem likely that this indirection -- parsing a string from a file into Q Exp, then splicing it into the module -- will help at all; ghc has to do the same thing in either case.

So maybe we really are stuck with the options of reading/parsing a bytestring at runtime (no), using cbits, or having really slow build times.  Hm.

**Comment by mpickering** [comment]
Could you not use Javascript FFI to achieve a similar effect to cbits when using GHCJS?

**Comment by jgm** [comment]
+++ Matthew Pickering [Feb 23 17 02:17 ]:
>   Could you not use Javascript FFI to achieve a similar effect to cbits
>   when using GHCJS?

Yes, probably.  So that might be one approach, if somebody
really wanted to compile this for js.  But it requires more
manually work in the package, new data files, etc.

I am frustrated by this problem with ghc, which has affected
several of my packages!  I don't understand why the compiler
gets so bogged down by something so simple:  a long literal list
of records.

**Comment by cartazio** [comment]
I think there's now a flag for simple list desugaring that might be useful
to prevent this problem.

If not, I think Matthew or I should escalate this to a ghc issue because
it's a valid need that is a pain to work around and ghc shouldn't be this
painful

**Comment by mpickering** [comment]
Have you tried the flag `-fsimple-list-literals`? I think that's the one Carter is talking about.

**Comment by mpickering** [comment]
It also might be better with 8.0.2 due to this commit - https://phabricator.haskell.org/rGHC19ab5256a1a0a4e7d4ed0d36973fb43eeeda447f

**Comment by mpickering** [comment]
Also this commit - https://phabricator.haskell.org/rGHC0db05941668814094c2b18b3d35e1deaed36c210

**Comment by jgm** [comment]
+++ Matthew Pickering [Feb 23 17 03:01 ]:
>   Have you tried the flag -fsimple-list-literals? I think that's the one
>   Carter is talking about.

Is that available in ghc 8.0.2?  It doesn't show up in
--show-options or a search of the user's guide...

**Comment by mpickering** [comment]
It appears not but the commit claims that its effect now applies to any list literal longer than 32 elements. 

I tried compiling `skylighting` and `texmath` and neither took a huge amount of time (3mins and 1min). How can I reproduce the problem?

**Comment by jgm** [comment]
Oh, I see from one of the linked issues that `simple-list-literals` was dropped in 8.0.1.
Anyway, it's ghc 8.0.1 and 8.0.2 that I've been using...
Note that the really painful part is profiling builds, which are much slower.

**Comment by jgm** [comment]
PS. skylighting has already been updated to use an indirect method where I store the literals as strings.  Before that, it was taking 10-30 minutes to compile on travis, and with profiling it simply timed out.  See the linked skylighting issue (jgm/skylighting#7), where an OpenSUSE maintainer notes that it was impossible to compile the profiling version of the library on ghc 8.0.2 even on machines with lots of RAM.

**Comment by jgm** [comment]
So, to reproduce, try a profiling build of skylighting-0.1.1.5.

**Comment by mpickering** [comment]
Which command are you using to do the profiling build? Where the cost centres are inserted could be quite important.

**Comment by jgm** [comment]
Originally, `stack install --profile` with no special options.
Then in 0.2 I added `ghc-prof-options: -fprof-auto-exported` to the cabal file.  This didn't help.  (Note that there aren't too many things exported in this package.)

**Comment by cartazio** [comment]
The original problem comes from building profiling way and using clang.

Gcc didn't have problems with the metadata stubs but clang would choke.

**Comment by jgm** [comment]
OK, I'll close this, as I'm now doubtful that there really is a good alternative to using cbits.

**Comment by cartazio** [comment]
... which never got scriptified to automatically generate the c bits right?

**Comment by jgm** [comment]
Yes, we really need to be generating the cbits
automatically.  I have not gotten around to doing this; if anyone
else would like to, of course it could be welcome.

>   ... which never got scriptified to automatically generate the c bits
>   right?
>   On Thu, Feb 23, 2017 at 10:34 AM John MacFarlane
>   <notifications@github.com>
>   wrote:
>   > OK, I'll close this, as I'm now doubtful that there really is a good
>   > alternative to using cbits.
