### ISSUE TITLE
\widehat not generating correct Word XML

### ISSUE THREAD

**Issue by DavidRGriswold** [jgm/texmath#98]
I am using pandoc version 1.19.2.1. If I make a markdown file test.md as below:

    The line below should have a hat over the entire word test

    *  $\widehat{test}$

Then use

    pandoc -o test.docx test.md

My word document only shows a hat in the middle of the word, even though the Word equation editor can easily put a hat over an entire word by typing (test)\hat  in the equation editor.

When I examine the XML, it seems that the pandoc output uses `<m:groupChr>` with `<m:chr m:val="^">` whereas if I create an equivalent line in the Word equation editor, the native output from Word uses `<m acc>` (interestingly with no `<m:chr>` tag at all - perhaps the hat is the default accent?) It seems to me that the accent is a more appropriate substitution for \widehat.

Here is the XML for both versions:

First, the one created by texmath (though I imagine Word inserted the font info when I saved it)
```xml
<m:oMath>
  <m:groupChr>
    <m:groupChrPr>
      <m:chr m:val="ˆ"/>
      <m:pos m:val="top"/>
      <m:vertJc m:val="bot"/>
      <m:ctrlPr>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
        </w:rPr>
      </m:ctrlPr>
    </m:groupChrPr>
    <m:e>
      <m:r>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
        </w:rPr>
        <m:t>test</m:t>
      </m:r>
    </m:e>
  </m:groupChr>
</m:oMath>
```
And next the one created by Word 2013 on Mac (it looks good on Word 2016 Windows, too. Haven't tried others.)

```xml
<m:oMath>
  <m:acc>
    <m:accPr>
      <m:ctrlPr>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
          <w:i/>
        </w:rPr>
      </m:ctrlPr>
    </m:accPr>
    <m:e>
      <m:r>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math"/>
        </w:rPr>
        <m:t>test</m:t>
      </m:r>
    </m:e>
  </m:acc>
</m:oMath>

**Comment by jgm** [comment]
This is pretty strange.  Here's what texmath generates for `\widehat{\text{test}}`:
```
<m:oMathPara>
  <m:oMathParaPr>
    <m:jc m:val="center" />
  </m:oMathParaPr>
  <m:oMath>
    <m:groupChr>
      <m:groupChrPr>
        <m:chr m:val="ˆ" />
        <m:pos m:val="top" />
        <m:vertJc m:val="bot" />
      </m:groupChrPr>
      <m:e>
        <m:r>
          <m:rPr>
            <m:sty m:val="p" />
          </m:rPr>
          <m:t>test</m:t>
        </m:r>
      </m:e>
    </m:groupChr>
  </m:oMath>
</m:oMathPara>
```
This displays with a small circumflex accent.  If you then remove the line `<m:chr m:val="ˆ" />`, then you get an accent over the whole thing -- only it's not a circumflex, but a brace.  If you then change `groupChr` to `acc` and `groupChrPr` to `accPr`, then you get a circumflex over the whole thing.  I have no idea why it decides to use a brace in the one case and a circumflex in the other, but if we're going to do this, we need some way of telling it explicitly what character to use...

**Comment by jgm** [comment]
From the OMML spec:

>22.1.2.2 accPr (Accent Properties)
>
> This element specifies the properties of the Accent function. If chr is omitted, the default accent character is U+0302 (COMBINING CIRCUMFLEX ACCENT).

So probably we just need to use U+0302 instead of `^` here.

**Comment by jgm** [comment]
Wait: we are using U+0302 here.

**Comment by jgm** [comment]
Hm. 
```
% texmath -t native
\widehat{\text{test}}
[EOver False (EText TextNormal "test") (ESymbol Accent "\710")]
```
So, 710, not 770 = 0x302.  I see what's happening now.

**Comment by jgm** [comment]
This is fixed now; I forgot to close this earlier.
